### ISSUE TITLE
Community question please give your input

### ISSUE THREAD

**Issue by BFH-ktt1** [reds-heig/logisim-evolution#200]
Each time you place an input or an output to your circuit it places it without a name. Hence, unless you use the auto-label functionality, you have to click on each to put a label to them.
Labels are required for the FPGA-comander, but are also nice if you use your circuit as sub-circuit as the labels appear in the symbol.
Would it make sense to add a functionality such that each time you place an input or output you are asked to specify a label (except of course when you have enabled the auto-label functionality [see #182]).
I'm very interested in your feed-back.

**Comment by maehne** [comment]
Personally, I have the habit to first place the ports and other principal blocks on the sheet before taking care of assigning labels to them in a systematic manner. Having them all in front of me helps me to choose systematic names. So, getting obliged to enter a port name would interrupt my workflow as I need to switch more frequently between mouse and keyboard.

That the naming is done in an own dialogue box instead of directly on the sheet when double clicking a port or block is also hampering efficient naming of the ports and blocks. Sometimes, it is therefore more efficient to enter the label in the properties panel right after placing a component. Entering the port/block label directly on the sheet after a double click on it should be relatively easy to implement as the "Edit text in circuit" function already works like that when you add illustrating comments to your circuit sheet.

Anyway, you have to keep moving constantly between the left library/properties panels and the sheet as the component selected for placing is unselected once it got placed. Sometimes, this may be desired, but it would make users more efficient if Logisim-evolution would remember the last chosen component to place if you double click it in the icon bar or component library, so that one could place several components right after another.
