### ISSUE TITLE
Windows 10, combinatoric analysis: inversion bars not correctly aligned over variables

### ISSUE THREAD

**Issue by maehne** [reds-heig/logisim-evolution#284]
In the Expression and Minimization tabs of the Combinational Analysis window, boolean equations are not correctly displayed when `Mathematical` is selected as notation. The inversion bars are not correctly ligned above the respective variables as can be seen in this screenshot:

![grafik](https://user-images.githubusercontent.com/1174243/66654513-aa3ea000-ec3a-11e9-9ca2-bb58587ae033.png)

I am running the latest Logisim-evolution version 3.1.0 built from the `develop` branch (commit 189f771) on Windows 10 with OpenJDK 13.

**Comment by simoc** [comment]
I think this bug is in method `ExpressionRenderData.style`.

The font `Monospaced` is used for the display of the expression in the Expression tab. Although ASCII characters in this font are fixed width, the Unicode dot symbol `\\u22C5` is not fixed width.

Before the width of the text on the screen is calculated in this method, all dots are replaced with underscores, and this will give an inaccurate width.

**Comment by maehne** [comment]
Thanks @simoc for fixing this issue with your PR #525! This issue can be closed.
