### ISSUE TITLE
Circuit appearance isn't persistent across files.

### ISSUE THREAD

**Issue by rhodeon** [reds-heig/logisim-evolution#397]
Creating a circuit and editing it's appearance works when using it in other circuits in the same file, but not when loaded as a library in another file.

For example, I made an implementation of the 7489 RAM IC and edited its appearance to be:
![in_file](https://user-images.githubusercontent.com/42483190/81121537-e0b97080-8f26-11ea-92c6-8eca7480f906.png)

It appears this way when used in other circuits in the same file.

But when loaded as a library in another file, it reverts to its appearance before modification:
![out_of_file](https://user-images.githubusercontent.com/42483190/81121628-1bbba400-8f27-11ea-8167-6f1782d6e602.png)

I tried it out on the original Logisim and it doesn't exhibit this behaviour. Version 2.14.6 of Evolution doesn't have this problem either.

**Comment by maehne** [comment]
Thanks for reporting the bug! I can reproduce the issue (see attached test case).

@BFH-ktt1: Could you have a look?

[bug397_testcase.zip](https://github.com/reds-heig/logisim-evolution/files/4585186/bug397_testcase.zip)

**Comment by BFH-ktt1** [comment]
This is my issue #334 , and on my todo list

**Comment by rhodeon** [comment]
Thanks for the response. Do you currently have an idea of the ETA for the next update?

**Comment by Triavanicus** [comment]
Where it changes
com.cburch.logisim.gui.menu.ProjectLibraryActions:177
package com.cburch.logisim.proj.Project:210
package com.cburch.logisim.file.LogisimFileActions.doIt (412)
com.cburch.logisim.fileLogisimFileActions.repair:435

It seams that when you load a library it will try to repair it, overwriting the appearance with the default appearance.

**Comment by Triavanicus** [comment]
If you create a method Circuit.java called setAppearance and set the appearance of the NewCirc, it won't work, at all, if circumvent the whole process and on line 460 of LogisimFileActions.java change it to `added.add(circ)` it will work just fine. So maybe if there was a way to repair it only if necessary, or something it will fix this bug.

**Comment by BFH-ktt1** [comment]
@Triavanicus 
Thanks a lot for your investigation, I took a quick look and remembered why the repair function is in place:
When loading a library also the standard libraries are loaded with the .circ file. If we would just do added.add(circ) all the components inside the circuit (except for the wires) would be linked against the libraries in the loaded "logisimfile" instead of the ones available in the "project". Meaning that we would have for example 3 different objects for a LED. In HDL-generation this causes severe problems.
The "repair" function will create a new circuit that links against the "project" instead if the "logisimFile". I forgot to update the appearance, and have to look into the details "how to copy" the correct appearance in the repair function (this might or not be a bit more involving).

**Comment by BFH-ktt1** [comment]
@Triavanicus , @rhodeon , I hope that this fixes the problem, I could not test all situations.
What I did is instead of making a new circuit, I replaced all factories of the components. This should be proper.

**Comment by Triavanicus** [comment]
It seems to work in my case.

**Comment by Triavanicus** [comment]
Just tested the old 7400 library, and it uses the correct appearance. This issue should be closed.

**Comment by rhodeon** [comment]
Can confirm it works as intended. Will be closing the issue now
